var CallbackID = {
    SCORE_UPDATE: 0,
    TARGET_SCORE_UPDATE: 1,
    LEVEL_UPDATE: 2,
    TIME_UPDATE: 3,
    BONUS_UPDATE: 4,
    BOMB_UPDATE: 5,
    WORM_UPDATE: 6,
    WORM_NUM: 7,
    WORM_USED: 8,
    DECORATIONS_RUBBER: 9,
    BEAR_RUBBER: 10,
    BEAR_DROP_LINE: 11,
    CHECK_WORM: 12,
    POOL_DEPLOY_BOMB: 13,
    BOMB_NUM: 14,
    BOMB_USED: 15
};